# Stage 1: Build Frontend (Vite/React)
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
# Tăng giới hạn RAM cho Node.js để tránh lỗi Out Of Memory khi build các project lớn
ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV VITE_API_BASE_URL=""
RUN npm run build

# Stage 2: Serve using Nginx
FROM nginx:alpine

# Xóa cấu hình mặc định của nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copy cấu hình nginx tùy chỉnh
COPY nginx.conf /etc/nginx/conf.d

# Copy file tĩnh từ quá trình build
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
